### PR TITLE
profile added

### PR DESCRIPTION
**Pull request by kwakie0511**

### CODE REVIEW

**Comment by zigen** [comment]
@kwakie0511 resolve conflicts

**Comment by kwakie0511** [comment]
> @kwakie0511 resolve conflicts

It says all checks have passed. Which conflict are you talking about?

**Comment by zigen** [comment]
Screenshot 2023-10-19 at 12 11 03

**Comment by zigen** [comment]
please don't delete other members profiles

**Review by zigen — APPROVED** [review]

**Comment by kwakie0511** [comment]
Am I good to go?

**Review by Naphann — CHANGES_REQUESTED** [review]
You need to run lint first, the format check fails.

**Review by Naphann — APPROVED** [review]
Looks good now!

**Pull request merged**
