### PR TITLE
Added bob's profile

### PR DESCRIPTION
**Pull request by funkeyteth**

### CODE REVIEW

**Review by zigen — APPROVED** [review]

**Review by zigen — CHANGES_REQUESTED** [review]
run `npm run lint` and then commit and push it.

> before commit your changes, you must run:
> $ npm run lint
> to format your code.

https://github.com/sfc-aqua/sfc-aqua.github.io#getting-started

**Comment by zigen** [comment]
and merge the latest change to resolve the conflict

**Comment by Sakumatcho** [comment]
Bob needs to clone.
So, I close this PR once and recreate PR.

**Comment by zigen** [comment]
i don't think she needs to close it...

**Pull request closed without merging**
